### ISSUE TITLE
Docs: add some details about keyboard shortcuts into README?

### ISSUE THREAD

**Issue by pzhlkj6612** [windyakin/streaming-plus-sequencer#43]
Hello, thanks for your work! This extension works great on eplus STREAMING+ player page in both Firefox and Chrome.

I noticed that you've processed keyboard events:

https://github.com/windyakin/streaming-plus-sequencer/blob/ea9f9c93a105cc09ae1fc5da48c2b20ef1df0fab/src/execute_script/script.ts#L49-L67

Maybe we can add some description about the keyboard shortcuts into README? New users may not know about it.

Thank you!

**Comment by windyakin** [comment]
Thank you. Added description on README.

https://github.com/windyakin/streaming-plus-sequencer/pull/44
